export const products = [
  {
    id: 1,
    name: "Banana",
    price: 4,
    type: "Produce",
    category: "Fruta",
    img: "../img/banana.png",
    promo: true,
    promoPrice: 2,
    components: ["Potássio", "Vitamina B6", "Vitamina C", "Folatos"],
  },
  {
    id: 2,
    name: "Morango",
    price: 7,
    type: "Produce",
    category: "Fruta",
    img: "../img/morango.png",
    promo: false,
    promoPrice: 5,
    components: ["Fibras", "Vitamina C", "Cálcio", "Ferro"],
  },
  {
    id: 3,
    name: "Maçã",
    price: 4,
    type: "Produce",
    category: "Fruta",
    img: "../img/maca.png",
    promo: true,
    promoPrice: 2,
    components: ["Potássio", "Vitamina A", "Vitamina E", "Vitamina C"],
  },
  {
    id: 4,
    name: "Pão",
    price: 5,
    type: "Bakery",
    category: "Pães",
    img: "../img/pao.png",
    promo: true,
    promoPrice: 3,
    components: ["Cálcio", "Sódio", "Fibra Alimentar", "Proteínas"],
  },
  {
    id: 5,
    name: "Leite",
    price: 7,
    type: "Dairy",
    category: "Leite",
    img: "../img/leite.png",
    promo: false,
    promoPrice: 1,
    components: ["Carboidratos", "Proteínas", "Gorduras totais"],
  },
  {
    id: 6,
    name: "Yogurt de Morango",
    price: 3,
    type: "Dairy",
    category: "Doce",
    img: "../img/yogurt-morango.png",
    promo: false,
    promoPrice: 2,
    components: ["Fibras", "Vitamina C", "Cálcio", "Ferro"],
  },
  {
    id: 7,
    name: "Bolo",
    price: 10,
    type: "Bakery",
    category: "Doce",
    img: "../img/bolo.png",
    promo: false,
    promoPrice: 1,
    components: ["Carboidratos", "Proteínas", "Gorduras totais"],
  },
  {
    id: 8,
    name: "Torta de Maçã",
    price: 4,
    type: "Bakery",
    category: "Doce",
    img: "../img/torta-maca.png",
    promo: true,
    promoPrice: 2,
    components: ["Fibras", "Vitamina C", "Cálcio", "Ferro"],
  },
];
